//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

pub use super::data::Entity as Data;
pub use super::domain::Entity as Domain;
pub use super::subdomain::Entity as Subdomain;
pub use super::validity::Entity as Validity;
