//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "subdomain")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub inscription: String,
    pub address: String,
    pub domain: String,
    pub subdomain: String,
    pub rtype: String,
    pub class: String,
    pub ttl: i32,
    pub rdata: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
